___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# Keras Basics

Welcome to the section on deep learning! We'll be using Keras with a TensorFlow backend to perform our deep learning operations.

This means we should get familiar with some Keras fundamentals and basics!

## Imports



꽃잎과 꽃받침 측정 값과 세가지 클래스 중 하나에 상응하는 레이블 포함

In [ ]:
import numpy as np

## Dataset

We will use the famous Iris Data set.
_____
More info on the data set:
https://en.wikipedia.org/wiki/Iris_flower_data_set

## Reading in the Data Set

We've already downloaded the dataset, its in this folder. So let's open it up.

In [ ]:
from sklearn.datasets import load_iris #scikit-learn 라이브러리에서 load_iris 함수를 불러오는 것
# Iris 데이터셋은 붓꽃의 꽃잎과 꽃받침의 길이와 너비를 측정한 데이터
# 세 가지 붓꽃 종(species)인 'setosa', 'versicolor', 'virginica'를 분류하기 위한 기능(feature)을 제공
#머신러닝과 패턴인식 연구에서 많이 사용

In [ ]:
iris = load_iris() # Iris 데이터셋을 로드

In [ ]:
type(iris)

sklearn.utils._bunch.Bunch

In [ ]:
print(iris.DESCR) #설명, 속성

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [ ]:
X = iris.data # Iris 데이터셋의 특징 데이터가 저장

In [ ]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
y = iris.target # 해당 특징 데이터에 대응하는 분류 클래스가 저장

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
#class 0 --> [1,0,0]
#class 1 --> [0,1,0]
#class 2 --> [1,0,1]
#원핫인코딩

In [ ]:
from keras.utils import to_categorical #to_categorical 함수는 분류 문제에서 레이블을 원-핫 인코딩(one-hot encoding) 형식으로 변환하는 데 사용
#예를 들어, 클래스가 3개인 경우:
#클래스 0은 [1, 0, 0]
#클래스 1은 [0, 1, 0]
#클래스 2는 [0, 0, 1]

In [ ]:
y = to_categorical(y)
#이전의 레이블 형태:

#클래스 0: 0
#클래스 1: 1
#클래스 2: 2

#새로운 원-핫 인코딩된 레이블 형태:

#클래스 0: [1, 0, 0]
#클래스 1: [0, 1, 0]
#클래스 2: [0, 0, 1]

In [ ]:
y.shape

(150, 3)

In [ ]:
y #원핫 인코딩

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

## Split the Data into Training and Test

Its time to split the data into a train/test set. Keep in mind, sometimes people like to split 3 ways, train/test/validation. We'll keep things simple for now. **Remember to check out the video explanation as to why we split and what all the parameters mean!**

In [ ]:
from sklearn.model_selection import train_test_split #데이터셋을 학습용과 테스트용으로 나누는 데 사용

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
#random_state=42: 데이터를 무작위로 분할할 때 사용되는 난수 발생기의 시드(seed) 값입니다. 이 값을 설정하면 실행할 때마다 동일한 분할이 생성되므로 결과를 재현할 수 있습니다.

In [ ]:
X_train

array([[5.7, 2.9, 4.2, 1.3],
       [7.6, 3. , 6.6, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 2. , 3.5, 1. ],
       [6.3, 2.7, 4.9, 1.8],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2.7, 4.2, 1.3],
       [5.1, 3.4, 1.5, 0.2],
       [5.7, 3. , 4.2, 1.2],
       [7.7, 3.8, 6.7, 2.2],
       [4.6, 3.2, 1.4, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.5, 5. , 2. ],
       [5.5, 4.2, 1.4, 0.2],
       [6. , 3. , 4.8, 1.8],
       [5.8, 2.7, 5.1, 1.9],
       [6. , 2.2, 4. , 1. ],
       [5.4, 3. , 4.5, 1.5],
       [6.2, 3.4, 5.4, 2.3],
       [5.5, 2.3, 4. , 1.3],
       [5.4, 3.9, 1.7, 0.4],
       [5. , 2.3, 3.3, 1. ],
       [6.4, 2.7, 5.3, 1.9],
       [5. , 3.3, 1.4, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 2.4, 3.8, 1.1],
       [6.7, 3

In [ ]:
X_test

array([[6.1, 2.8, 4.7, 1.2],
       [5.7, 3.8, 1.7, 0.3],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.9, 4.5, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [5.4, 3.4, 1.5, 0.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.9, 3.1, 5.1, 2.3],
       [6.2, 2.2, 4.5, 1.5],
       [5.8, 2.7, 3.9, 1.2],
       [6.5, 3.2, 5.1, 2. ],
       [4.8, 3. , 1.4, 0.1],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.1, 3.8, 1.5, 0.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.5, 3. , 5.8, 2.2],
       [5.6, 2.5, 3.9, 1.1],
       [5.7, 2.8, 4.5, 1.3],
       [6.4, 2.8, 5.6, 2.2],
       [4.7, 3.2, 1.6, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [5. , 3.4, 1.6, 0.4],
       [6.4, 2.8, 5.6, 2.1],
       [7.9, 3.8, 6.4, 2. ],
       [6.7, 3. , 5.2, 2.3],
       [6.7, 2.5, 5.8, 1.8],
       [6.8, 3.2, 5.9, 2.3],
       [4.8, 3. , 1.4, 0.3],
       [4.8, 3.1, 1.6, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.7, 3.1, 4.4, 1.4],
       [4.8, 3.4, 1.6, 0.2],
       [4.4, 3

In [ ]:
y_train

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0

## Standardizing the Data

Usually when using Neural Networks, you will get better performance when you standardize the data. Standardization just means normalizing the values to all fit between a certain range, like 0-1, or -1 to 1.

The scikit learn library also provides a nice function for this.

http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html

In [ ]:
from sklearn.preprocessing import MinMaxScaler #모든 것을 0과 1사이의 값으로 만드는 것
#MinMaxScaler는 주어진 범위 (일반적으로 0과 1 사이) 내에서 각 특징을 스케일링합니다.
#이렇게 하면 데이터의 분포가 원하는 범위로 조정되어 모델의 성능을 향상시키거나 최적화 알고리즘이 더 잘 수렴되도록 할 수 있습니다.

In [ ]:
scaler_object = MinMaxScaler()

In [ ]:
scaler_object.fit(X_train) #X_train에 대해 스케일링을 적용하기 위해 모델을 피팅(fitting)

MinMaxScaler()

In [ ]:
scaled_X_train = scaler_object.transform(X_train) #transform 메서드는 주어진 데이터에 대해 스케일링을 적용하는 메서드

In [ ]:
scaled_X_test = scaler_object.transform(X_test)

Ok, now we have the data scaled!

In [ ]:
X_train.max()

7.7

In [ ]:
scaled_X_train.max()

1.0

In [ ]:
X_train

array([[5.7, 2.9, 4.2, 1.3],
       [7.6, 3. , 6.6, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 2. , 3.5, 1. ],
       [6.3, 2.7, 4.9, 1.8],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2.7, 4.2, 1.3],
       [5.1, 3.4, 1.5, 0.2],
       [5.7, 3. , 4.2, 1.2],
       [7.7, 3.8, 6.7, 2.2],
       [4.6, 3.2, 1.4, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.5, 5. , 2. ],
       [5.5, 4.2, 1.4, 0.2],
       [6. , 3. , 4.8, 1.8],
       [5.8, 2.7, 5.1, 1.9],
       [6. , 2.2, 4. , 1. ],
       [5.4, 3. , 4.5, 1.5],
       [6.2, 3.4, 5.4, 2.3],
       [5.5, 2.3, 4. , 1.3],
       [5.4, 3.9, 1.7, 0.4],
       [5. , 2.3, 3.3, 1. ],
       [6.4, 2.7, 5.3, 1.9],
       [5. , 3.3, 1.4, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 2.4, 3.8, 1.1],
       [6.7, 3

In [ ]:
scaled_X_train

array([[0.41176471, 0.40909091, 0.55357143, 0.5       ],
       [0.97058824, 0.45454545, 0.98214286, 0.83333333],
       [0.38235294, 0.45454545, 0.60714286, 0.58333333],
       [0.23529412, 0.68181818, 0.05357143, 0.04166667],
       [1.        , 0.36363636, 1.        , 0.79166667],
       [0.44117647, 0.31818182, 0.53571429, 0.375     ],
       [0.26470588, 0.63636364, 0.05357143, 0.04166667],
       [0.20588235, 0.68181818, 0.03571429, 0.08333333],
       [0.23529412, 0.81818182, 0.14285714, 0.125     ],
       [0.20588235, 0.        , 0.42857143, 0.375     ],
       [0.58823529, 0.31818182, 0.67857143, 0.70833333],
       [0.14705882, 0.63636364, 0.14285714, 0.04166667],
       [0.20588235, 0.45454545, 0.08928571, 0.04166667],
       [0.23529412, 0.59090909, 0.10714286, 0.16666667],
       [0.38235294, 0.31818182, 0.55357143, 0.5       ],
       [0.23529412, 0.63636364, 0.07142857, 0.04166667],
       [0.41176471, 0.45454545, 0.55357143, 0.45833333],
       [1.        , 0.81818182,

## Building the Network with Keras

Let's build a simple neural network!

In [ ]:
from keras.models import Sequential #Sequential 모델은 신경망을 순차적으로 쌓는 데 사용됩니다.
#이는 입력층, 은닉층, 출력층 등을 순차적으로 쌓아 간단한 모델부터 복잡한 모델까지 만들 수 있도록 합니다.

from keras.layers import Dense #Dense 층은 fully connected 층을 의미하며, 모든 입력 뉴런과 출력 뉴런이 연결된 층입니다.
#이 층은 신경망에서 가장 일반적으로 사용되는 층 중 하나이며, 입력과 출력 사이에 있는 모든 뉴런이 서로 연결되어 있습니다.

In [ ]:
#다층 퍼셉트론(Multi-Layer Perceptron, MLP)을 구축하고 컴파일하는 과정

model = Sequential()
# 각각 8개의 뉴런으로 이루어진 2개의 은닉층과 3개의 출력 뉴런으로 이루어진 출력층으로 구성
model.add(Dense(8, input_dim=4, activation='relu')) #첫 번째 은닉층을 추가합니다. 이 층은 8개의 뉴런을 가지며, 입력 차원은 4입니다.
#activation은 활성화 함수로 ReLU 함수를 사용합니다.

model.add(Dense(8, input_dim=4, activation='relu')) #두 번째 은닉층을 추가합니다.

model.add(Dense(3, activation='softmax')) #출력층을 추가합니다. 이 층은 3개의 뉴런을 가지며, 클래스 수에 해당하는 출력 차원을 가집니다.
#activation은 확률값을 출력하기 위해 softmax 함수를 사용
#일반적으로 분류 문제에서는 마지막 층에서 softmax 함수를 사용하여 모델이 각 클래스에 속할 확률을 예측할 수 있도록 합니다.

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
#모델을 컴파일합니다. 이때 손실 함수로 categorical crossentropy를, 옵티마이저로는 Adam을 사용합니다. 성능 평가 지표로는 정확도(accuracy)를 사용

In [ ]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_15 (Dense)            (None, 8)                 40        
                                                                 
 dense_16 (Dense)            (None, 8)                 72        
                                                                 
 dense_17 (Dense)            (None, 3)                 27        
                                                                 
Total params: 139 (556.00 Byte)
Trainable params: 139 (556.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


## Fit (Train) the Model

In [ ]:
# Play around with number of epochs as well!
model.fit(scaled_X_train,y_train,epochs=150, verbose=2)
#fit() 메서드는 학습 데이터와 레이블 데이터를 받아서 모델을 학습시킵니다.
#여기서 scaled_X_train은 스케일링된 특징 데이터이고, y_train은 원-핫 인코딩된 레이블 데이터입니다.
#erbose=2는 학습 진행 상황을 얼마나 자세하게 출력할 것인지를 지정하는 매개변수입니다.
#verbose가 2로 설정되면 에포크 당 한 줄의 출력이 나타납니다.

Epoch 1/150
4/4 - 1s - loss: 1.1630 - accuracy: 0.3100 - 718ms/epoch - 180ms/step
Epoch 2/150
4/4 - 0s - loss: 1.1540 - accuracy: 0.3100 - 11ms/epoch - 3ms/step
Epoch 3/150
4/4 - 0s - loss: 1.1455 - accuracy: 0.3000 - 12ms/epoch - 3ms/step
Epoch 4/150
4/4 - 0s - loss: 1.1380 - accuracy: 0.3000 - 11ms/epoch - 3ms/step
Epoch 5/150
4/4 - 0s - loss: 1.1315 - accuracy: 0.3000 - 13ms/epoch - 3ms/step
Epoch 6/150
4/4 - 0s - loss: 1.1252 - accuracy: 0.3000 - 11ms/epoch - 3ms/step
Epoch 7/150
4/4 - 0s - loss: 1.1193 - accuracy: 0.3100 - 11ms/epoch - 3ms/step
Epoch 8/150
4/4 - 0s - loss: 1.1140 - accuracy: 0.3100 - 12ms/epoch - 3ms/step
Epoch 9/150
4/4 - 0s - loss: 1.1090 - accuracy: 0.3100 - 11ms/epoch - 3ms/step
Epoch 10/150
4/4 - 0s - loss: 1.1040 - accuracy: 0.3100 - 12ms/epoch - 3ms/step
Epoch 11/150
4/4 - 0s - loss: 1.0993 - accuracy: 0.3100 - 12ms/epoch - 3ms/step
Epoch 12/150
4/4 - 0s - loss: 1.0945 - accuracy: 0.3100 - 11ms/epoch - 3ms/step
Epoch 13/150
4/4 - 0s - loss: 1.0897 - accurac

## Predicting New Unseen Data

Let's see how we did by predicting on **new data**. Remember, our model has **never** seen the test data that we scaled previously! This process is the exact same process you would use on totally brand new data. For example , a brand new bank note that you just analyzed .

In [ ]:
scaled_X_test #스케일링된 데이터

array([[ 0.52941176,  0.36363636,  0.64285714,  0.45833333],
       [ 0.41176471,  0.81818182,  0.10714286,  0.08333333],
       [ 1.        ,  0.27272727,  1.03571429,  0.91666667],
       [ 0.5       ,  0.40909091,  0.60714286,  0.58333333],
       [ 0.73529412,  0.36363636,  0.66071429,  0.54166667],
       [ 0.32352941,  0.63636364,  0.07142857,  0.125     ],
       [ 0.38235294,  0.40909091,  0.44642857,  0.5       ],
       [ 0.76470588,  0.5       ,  0.71428571,  0.91666667],
       [ 0.55882353,  0.09090909,  0.60714286,  0.58333333],
       [ 0.44117647,  0.31818182,  0.5       ,  0.45833333],
       [ 0.64705882,  0.54545455,  0.71428571,  0.79166667],
       [ 0.14705882,  0.45454545,  0.05357143,  0.        ],
       [ 0.35294118,  0.68181818,  0.03571429,  0.04166667],
       [ 0.17647059,  0.5       ,  0.07142857,  0.        ],
       [ 0.23529412,  0.81818182,  0.07142857,  0.08333333],
       [ 0.58823529,  0.59090909,  0.64285714,  0.625     ],
       [ 0.64705882,  0.

In [ ]:
# Spits out probabilities by default.
predictions_x = model.predict(scaled_X_test)
#model.predict() 함수를 사용하여 스케일링된 테스트 데이터에 대한 예측 확률을 얻습니다.
#이 예측 확률은 각 샘플이 각 클래스에 속할 확률을 나타냅니다.
#예를 들어, 세 개의 클래스가 있다면 각 샘플에 대해 세 개의 확률이 반환됩니다.

2/2 [==============================] - 0s 5ms/step


In [ ]:
predictions_x

array([[0.23309591, 0.42141813, 0.3454859 ],
       [0.9847273 , 0.01209715, 0.00317552],
       [0.20430565, 0.32450768, 0.47118664],
       [0.22284108, 0.41815338, 0.35900566],
       [0.24632314, 0.42265788, 0.3310189 ],
       [0.97350305, 0.02048711, 0.00600977],
       [0.2664781 , 0.43456492, 0.29895708],
       [0.20346381, 0.37879506, 0.41774103],
       [0.21413955, 0.39017752, 0.39568287],
       [0.24336582, 0.44347152, 0.3131625 ],
       [0.2061033 , 0.38927835, 0.40461838],
       [0.9592898 , 0.03029318, 0.01041711],
       [0.9832078 , 0.01323067, 0.00356149],
       [0.9625701 , 0.02801795, 0.00941193],
       [0.9828483 , 0.0134973 , 0.00365452],
       [0.23194002, 0.42914104, 0.33891892],
       [0.19847974, 0.354228  , 0.44729233],
       [0.23566195, 0.43836966, 0.32596835],
       [0.21948022, 0.4163854 , 0.36413428],
       [0.19858031, 0.35373136, 0.4476884 ],
       [0.95969546, 0.03001266, 0.01029187],
       [0.20276402, 0.38974503, 0.40749094],
       [0.

In [ ]:
predicted_classes_x = np.argmax(predictions_x, axis=1)
#예측 확률이 담긴 배열인 predictions_x에서 각 행에서 최댓값의 인덱스를 찾아 예측된 클래스로 변환하는 것입니다.
#axis=1은 각 행에서 최댓값의 인덱스를 찾겠다는 것을 의미합니다.

In [ ]:
predicted_classes_x #원핫인코딩 값이 아닌 위치값으로 출력됐음. 그래서 y_test도 이렇게 변환해야 함.

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 1, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [ ]:
# model.predict_classes(scaled_X_test)

In [ ]:
# y_test도 위에처럼 바꾸기

In [ ]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

# Evaluating Model Performance

So how well did we do? How do we actually measure "well". Is 95% accuracy good enough? It all depends on the situation. Also we need to take into account things like recall and precision. Make sure to watch the video discussion on classification evaluation before running this code!

In [ ]:
# model.metrics_names

In [ ]:
model.evaluate(x=scaled_X_test,y=y_test)

2/2 [==============================] - 0s 8ms/step - loss: 0.5327 - accuracy: 0.9600


[0.5326591730117798, 0.9599999785423279]

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
#confusion_matrix: 혼동 행렬(Confusion Matrix)을 계산하는 함수로, 예측된 클래스와 실제 클래스 간의 오차를 행렬로 표현합니다.
#이를 통해 모델의 성능을 평가할 때 사용됩니다.

#classification_report: 분류 보고서(Classification Report)를 생성하는 함수로,
#정밀도(precision), 재현율(recall), F1-점수(F1-score) 등을 포함한 다양한 분류 지표를 계산하여 제공합니다.

#accuracy_score: 정확도(Accuracy)를 계산하는 함수로, 모델의 전체적인 분류 정확도를 나타냅니다.

In [ ]:
predictions_x=model.predict(scaled_X_test)

2/2 [==============================] - 0s 5ms/step


In [ ]:
predicted_classes_x = np.argmax(predictions_x, axis=1)
predicted_classes_x

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 1, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [ ]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [ ]:
confusion_matrix(y_test.argmax(axis=1),predicted_classes_x)
#이 행렬은 각 행은 실제 클래스를, 각 열은 예측된 클래스를 나타내며,
#행렬의 값은 해당 클래스가 얼마나 맞게 예측되었는지를 나타냅니다.

array([[19,  0,  0],
       [ 0, 14,  1],
       [ 0,  1, 15]])

In [ ]:
print(classification_report(y_test.argmax(axis=1),predicted_classes_x))
#정밀도(precision), 재현율(recall), F1-점수(F1-score) 등의 다양한 분류 지표가 포함

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      0.93      0.93        15
           2       0.94      0.94      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [ ]:
accuracy_score(y_test.argmax(axis=1),predicted_classes_x)

0.96

## Saving and Loading Models

Now that we have a model trained, let's see how we can save and load it.

In [ ]:
model.save('myfirstmodel.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [ ]:
from keras.models import load_model

In [ ]:
newmodel = load_model('myfirstmodel.h5')

In [ ]:
newprediction_X=newmodel.predict(scaled_X_test)

2/2 [==============================] - 0s 6ms/step


In [ ]:
np.argmax(newprediction_X, axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 1, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

Great job! You now know how to preprocess data, train a neural network, and evaluate its classification performance!